language: python
python: '2.7'

branches:
  only:
    - incrementci
    - master

env:
  global:
    - exit_code=0
    - number_per_job=2
    - message=()
    - ANSIBLE_VERSION=latest
    - ANSIBLE_CONFIG=/home/travis/.ansible/ansible.cfg
    #- ANSIBLE_VERSION=2.4.2.0
  matrix:
    - id=1
    - id=2
    - id=3
    - id=4
    - id=5
    - id=6

before_install:
  - sudo apt-get update -qq
  - run_test(){
      file=$1;
      test_name=${file##./};
      test_name=${test_name%%.yml};
      delete_resource_group=${2:-true};
      resource_group=${3:-sampletest$(date +%s)};

      echo Run playbook $file;

      travis_wait 50 ansible-playbook $file --extra-vars "{\"azure_subscription_id\":$AZURE_SUBSCRIPTION_ID,\"azure_tenant\":$AZURE_TENANT,\"azure_client_id\":$AZURE_CLIENT_ID,\"resource_group_name\":$resource_group}";

      if [ $? -ne 0 ]; then
        echo test $file failed;
        message+=($file);
        export exit_code=1;
      fi;

      if [ "$delete_resource_group" == true ]; then
        travis_wait 50 ansible-playbook ./__helpers/__delete_test_resource_group.yml --extra-vars "{\"azure_subscription_id\":$AZURE_SUBSCRIPTION_ID,\"azure_tenant\":$AZURE_TENANT,\"azure_client_id\":$AZURE_CLIENT_ID,\"resource_group_name\":$resource_group}";
      fi;
    }


  - scan_test() {
      end=$((id * number_per_job));
      start=$((end - number_per_job));

      branch=$TRAVIS_BRANCH;

      echo branch is $branch;
      git pull;

      diffstr=$(git diff $branch remotes/origin/master --name-only  -- '*.yml' --no-pager);
      changedfiles=($diffstr);
      excludedList="vm_create_existingvnet_deployjavaapp.yml .travis.yml";

      echo start = $start, end = $end, list_lenth = ${#changedfiles[@]};

      echo changed file count is $list_lenth, list is $changedfiles;

      for (( i = $start; i < $end; i++ )); do
        echo file is ${#changedfiles[@]}
        if [ "$i" -lt "${#changedfiles[@]}" ]; then
          excluded=false;
          for item in ${excludedList[*]}; do
            if [ "${changedfiles[$i]}" == "$item" ]; then
              excluded=true;
              break;
            fi
          done;
          if [ "$excluded" == false ]; then
            run_test ${changedfiles[$i]};	
          fi
        fi
      done;
    }

install:
  - sudo apt-get install -y git
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - apt-cache policy docker-ce
  - sudo apt-get install -y docker-ce
  - sudo usermod -aG docker ${USER}
  - sudo apt-get install -y default-jdk
  - sudo apt-get install -y maven sshpass

  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible[azure]; else pip
    install ansible[azure]==$ANSIBLE_VERSION; fi
  - ansible --version
  - ansible-galaxy install Azure.azure_preview_modules
  - pip install -I -r ~/.ansible/roles/Azure.azure_preview_modules/files/requirements-azure.txt
  - pip install docker
  - pip freeze
  - cp -f ./vmss/ansible.cfg /home/travis/.ansible

  - git clone https://github.com/Azure-Samples/ansible-playbooks.git
  - cd ansible-playbooks
  - git checkout $TRAVIS_BRANCH

script:
  - scan_test
  - exit $exit_code

notifications:
  email:
    - yungez@microsoft.com
    - yuwzho@microsoft.com	
    - zikalino@microsoft.com