language: python
python: '2.7'

branches:
  only:
    - master

env:
  global:
    - exit_code=0
    - number_per_job=2
    - message=()
    - ANSIBLE_VERSION=latest
    #- ANSIBLE_VERSION=2.4.2.0
  matrix:
    - id=1
    - id=2
    - id=3
    - id=4
    - id=5
    - id=6

before_install:
  - sudo apt-get update -qq
  - run_test(){
      file=$1;
      test_name=${file##./};
      test_name=${test_name%%.yml};
      resource_group="${test_name}$(date +%s)";
      echo Run playbook $file;

      travis_wait 50 ansible-playbook $file --extra-vars "{\"azure_subscription_id\":$AZURE_SUBSCRIPTION_ID,\"azure_tenant\":$AZURE_TENANT,\"azure_client_id\":$AZURE_CLIENT_ID,\"resource_group_name\":$resource_group}";

      if [ $? -ne 0 ]; then
        echo test $file failed;
        message+=($file);
        export exit_code=1;
      fi;

      travis_wait 50 ansible-playbook ./__helpers/__delete_test_resource_group.yml --extra-vars "{\"azure_subscription_id\":$AZURE_SUBSCRIPTION_ID,\"azure_tenant\":$AZURE_TENANT,\"azure_client_id\":$AZURE_CLIENT_ID,\"resource_group_name\":$resource_group}";
    }


  - scan_test() {
      end=$((id * number_per_job));
      start=$((end - number_per_job));

      liststr=./*.yml;
      list=($liststr);

      excludedList=("./vm_create_existingvnet_deployjavaapp.yml")
      echo start = $start, end = $end, list_lenth = ${#list[@]};

      for (( i = $start; i < $end; i++ )); do	
        if [ "$i" -lt "${#list[@]}" ]; then
          excluded=false;
          for item in ${excludedList[*]}; do
            if [ "${list[$i]}" == "$item" ]; then
              excluded=true;
              break;
            fi
          done;
          if [ "$excluded" == false ]; then
            run_test ${list[$i]};	
          fi
        fi
      done;

    }

install:
  - sudo apt-get install -y git
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - apt-cache policy docker-ce
  - sudo apt-get install -y docker-ce
  - sudo usermod -aG docker ${USER}
  - sudo apt-get install -y default-jdk
  - sudo apt-get install -y maven

  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible[azure]; else pip
    install ansible[azure]==$ANSIBLE_VERSION; fi
  - ansible --version
  - ansible-galaxy install Azure.azure_preview_modules
  - pip install -I -r ~/.ansible/roles/Azure.azure_preview_modules/files/requirements-azure.txt
  - pip install docker
  - pip freeze

script:
  - scan_test
  - exit $exit_code

notifications:
  email:
    - yungez@microsoft.com
    - yuwzho@microsoft.com
    - zikalino@microsoft.com
